"""
evidence_engine.py
------------------
CNIS Phase 3H: Deterministic Evidence & Provenance Engine.

Compiles a mathematically grounded, fully traceable evidence layer connecting
every intelligence finding (entities, relationships, network metrics, anomalies,
temporal events, locations, and reports) to actual source records and deterministic
analytical transformations.

Answers the fundamental investigator question:
    "Why does CNIS show this?"

Strict Epistemic Principles:
  1. EvidenceClassification is distinct from EpistemicStatus.
  2. EpistemicStatus values: OBSERVED, DERIVED, SIGNAL, REVIEW_REQUIRED.
  3. Co-occurrence in source records is NOT proof of a criminal relationship.
  4. Anomaly signals are NOT proof of crime.
  5. Network centrality is NOT proof of guilt or hierarchy.
  6. Temporal proximity is NOT proof of coordination.
  7. Location overlap is NOT proof of a meeting.
  8. Raw source excerpts are 100% byte-for-byte verbatim from ingested records.
  9. Inverted indices provide average-case O(1) lookups.
  10. Zero external runtime LLM/API dependencies; 100% deterministic and idempotent.
"""

from __future__ import annotations
import re
from dataclasses import dataclass, field
from typing import Dict, List, Any, Optional, Tuple, Set


# ── 1. Epistemic Classifications & Statuses ───────────────────────────────────

class EvidenceClassification:
    """
    Categorizes the structural nature of an intelligence artifact.
    """
    SOURCE_RECORD = "SOURCE_RECORD"
    ENTITY_OBSERVATION = "ENTITY_OBSERVATION"
    RELATIONSHIP = "RELATIONSHIP"
    ANOMALY_SIGNAL = "ANOMALY_SIGNAL"
    NETWORK_METRIC = "NETWORK_METRIC"
    TEMPORAL_OBSERVATION = "TEMPORAL_OBSERVATION"
    LOCATION_OBSERVATION = "LOCATION_OBSERVATION"
    ENTITY_RESOLUTION = "ENTITY_RESOLUTION"

    ALL = {
        SOURCE_RECORD,
        ENTITY_OBSERVATION,
        RELATIONSHIP,
        ANOMALY_SIGNAL,
        NETWORK_METRIC,
        TEMPORAL_OBSERVATION,
        LOCATION_OBSERVATION,
        ENTITY_RESOLUTION,
    }


class EpistemicStatus:
    """
    Categorizes the epistemic foundation of an intelligence claim:
      - OBSERVED: Directly present in a source record.
      - DERIVED: Produced by deterministic mathematical/graph computation.
      - SIGNAL: Produced by an analytical detector (e.g. anomaly heuristics/models).
      - REVIEW_REQUIRED: Ambiguity detected requiring authorized human review.
    """
    OBSERVED = "OBSERVED"
    DERIVED = "DERIVED"
    SIGNAL = "SIGNAL"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"

    ALL = {
        OBSERVED,
        DERIVED,
        SIGNAL,
        REVIEW_REQUIRED,
    }


# ── 2. Standardized Epistemic Limitations ────────────────────────────────────

LIMITATIONS_RELATIONSHIP = (
    "Documented co-occurrence across intelligence case records indicates network association "
    "within reported incidents. Co-occurrence in source records does not prove criminal partnership "
    "or illicit coordination."
)

LIMITATIONS_ANOMALY = (
    "Investigative anomaly signal only. Analytical signal generated by deterministic pattern detection rules or statistical models. "
    "Anomaly flags represent investigative leads and do not constitute legal evidence or proof of unlawful activity."
)

LIMITATIONS_NETWORK_METRIC = (
    "Centrality reflects network structure and topological position within the ingested multi-graph. "
    "Graph centrality measures quantify topological structural position and information flow within "
    "the ingested multi-graph. Centrality metrics do not denote criminal hierarchy, guilt, or operational intent."
)

LIMITATIONS_TEMPORAL = (
    "Chronological sequencing reflects recorded dates of incident reporting in intelligence feeds. "
    "Temporal proximity indicates chronological correlation, not verified coordination."
)

LIMITATIONS_LOCATION = (
    "Geographical presence indicates reported operational or incident site co-occurrence. "
    "Spatial overlap does not confirm in-person meetings or verified physical contact."
)

LIMITATIONS_ENTITY_RESOLUTION = (
    "Identity resolution is an analytical matching aid based on multi-signal compatibility. "
    "Candidate pairs flagged with REVIEW_REQUIRED require investigator corroboration before identity consolidation."
)

LIMITATIONS_SOURCE_RECORD = (
    "Verbatim intelligence record content ingested from external source feeds. Accuracy is contingent "
    "on source agency collection integrity."
)


# ── 3. Helper Functions for Deterministic ID Generation ───────────────────────

def _slug(val: str) -> str:
    """Creates a deterministic, URL-safe slug from a string."""
    s = re.sub(r"[^A-Za-z0-9]+", "-", str(val).strip()).strip("-").upper()
    return s or "UNKNOWN"


def canonical_pair(u: str, v: str) -> Tuple[str, str]:
    """Canonicalizes an unordered entity pair so (A, B) and (B, A) are identical."""
    u_clean = u.strip()
    v_clean = v.strip()
    return (u_clean, v_clean) if u_clean <= v_clean else (v_clean, u_clean)


# ── 4. Evidence Data Models ───────────────────────────────────────────────────

@dataclass
class EvidenceReference:
    """Pointer to another entity, record, anomaly, or evidence item."""
    target_id: str
    target_type: str  # "RECORD" | "ENTITY" | "ANOMALY" | "EVIDENCE" | "CASE" | "LOCATION"
    description: str

    def to_dict(self) -> Dict[str, Any]:
        return {
            "target_id": self.target_id,
            "target_type": self.target_type,
            "description": self.description,
        }


@dataclass
class EvidenceItem:
    """
    Atomic, deterministic evidence container answering:
      - What is the finding?
      - What type of evidence is this?
      - Which source records support it?
      - Which entities are involved?
      - What timestamp/context is relevant?
      - Which deterministic analytical method produced it?
      - Why is it relevant?
      - What limitations apply?
    """
    evidence_id: str
    evidence_type: str  # EvidenceClassification
    epistemic_status: str  # EpistemicStatus
    finding: str
    source_records: List[str]
    raw_excerpts: List[Dict[str, Any]]
    entities: List[str]
    temporal_context: Optional[str]
    spatial_context: Optional[str]
    analytical_method: str
    rationale: str
    limitations: str
    references: List[EvidenceReference] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "evidence_id": self.evidence_id,
            "evidence_type": self.evidence_type,
            "epistemic_status": self.epistemic_status,
            "finding": self.finding,
            "source_records": self.source_records,
            "raw_excerpts": self.raw_excerpts,
            "entities": self.entities,
            "temporal_context": self.temporal_context,
            "spatial_context": self.spatial_context,
            "analytical_method": self.analytical_method,
            "rationale": self.rationale,
            "limitations": self.limitations,
            "references": [r.to_dict() for r in self.references],
            "metadata": self.metadata,
        }


@dataclass
class EvidenceTrace:
    """
    Hierarchical trace explaining step-by-step how a signal or derived finding
    emerged from raw source records.
    """
    target_id: str
    target_type: str
    evidence_id: str
    steps: List[Dict[str, Any]] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "target_id": self.target_id,
            "target_type": self.target_type,
            "evidence_id": self.evidence_id,
            "steps": self.steps,
        }


# ── 5. Evidence Engine & Inverted Indices ─────────────────────────────────────

class EvidenceEngine:
    """
    Deterministic provenance and evidence compilation layer.
    Indexes all intelligence findings with average-case O(1) lookups:
      - by evidence_id
      - by entity
      - by record
      - by anomaly
      - by canonical relationship pair (u, v)
      - by evidence classification
    """

    def __init__(self):
        self.items: Dict[str, EvidenceItem] = {}  # evidence_id -> EvidenceItem
        self.index_by_entity: Dict[str, Set[str]] = {}  # entity -> set of evidence_ids
        self.index_by_record: Dict[str, Set[str]] = {}  # record_id -> set of evidence_ids
        self.index_by_anomaly: Dict[str, str] = {}  # anomaly_id -> evidence_id
        self.index_by_relationship: Dict[Tuple[str, str], str] = {}  # canonical (u, v) -> evidence_id
        self.index_by_relationship_lower: Dict[Tuple[str, str], str] = {}  # canonical (u_lower, v_lower) -> evidence_id
        self.index_by_type: Dict[str, Set[str]] = {}  # classification -> set of evidence_ids

    def register_item(self, item: EvidenceItem):
        """Registers an evidence item and populates all inverted indices."""
        eid = item.evidence_id
        self.items[eid] = item

        # Index by classification
        self.index_by_type.setdefault(item.evidence_type, set()).add(eid)

        # Index by source records
        for rid in item.source_records:
            self.index_by_record.setdefault(rid, set()).add(eid)

        # Index by entities
        for ent in item.entities:
            self.index_by_entity.setdefault(ent, set()).add(eid)

        # Index by relationship if applicable
        if item.evidence_type == EvidenceClassification.RELATIONSHIP and len(item.entities) >= 2:
            cp = canonical_pair(item.entities[0], item.entities[1])
            self.index_by_relationship[cp] = eid
            u_low = cp[0].strip().lower()
            v_low = cp[1].strip().lower()
            cp_low = (u_low, v_low) if u_low <= v_low else (v_low, u_low)
            self.index_by_relationship_lower[cp_low] = eid

        # Index by anomaly if applicable
        if item.evidence_type == EvidenceClassification.ANOMALY_SIGNAL and "anomaly_id" in item.metadata:
            self.index_by_anomaly[item.metadata["anomaly_id"]] = eid

    def get_item(self, evidence_id: str) -> Optional[EvidenceItem]:
        """Average-case O(1) lookup by evidence_id."""
        return self.items.get(evidence_id)

    def get_by_entity(self, entity: str) -> List[EvidenceItem]:
        """Average-case O(1) set lookup for all evidence items referencing an entity."""
        eids = self.index_by_entity.get(entity, set())
        # Also check case-insensitive match if exact match not found
        if not eids:
            ent_lower = entity.lower()
            for k, s in self.index_by_entity.items():
                if k.lower() == ent_lower:
                    eids = s
                    break
        return [self.items[eid] for eid in sorted(eids) if eid in self.items]

    def get_by_record(self, record_id: str) -> List[EvidenceItem]:
        """Average-case O(1) set lookup for all evidence items referencing a record."""
        eids = self.index_by_record.get(record_id, set())
        return [self.items[eid] for eid in sorted(eids) if eid in self.items]

    def get_by_anomaly(self, anomaly_id: str) -> Optional[EvidenceItem]:
        """Average-case O(1) lookup for evidence supporting an anomaly."""
        eid = self.index_by_anomaly.get(anomaly_id)
        return self.items.get(eid) if eid else None

    def get_by_relationship(self, u: str, v: str) -> Optional[EvidenceItem]:
        """Average-case O(1) lookup for relationship evidence between two entities."""
        cp = canonical_pair(u, v)
        eid = self.index_by_relationship.get(cp)
        if not eid:
            u_low = u.strip().lower()
            v_low = v.strip().lower()
            cp_low = (u_low, v_low) if u_low <= v_low else (v_low, u_low)
            eid = self.index_by_relationship_lower.get(cp_low)
        return self.items.get(eid) if eid else None

    @property
    def inverted_index_id(self) -> Dict[str, EvidenceItem]:
        """Direct O(1) map of evidence_id to EvidenceItem."""
        return self.items

    @property
    def all_items(self) -> List[EvidenceItem]:
        """List of all registered evidence items."""
        return list(self.items.values())

    def get_evidence_by_classification(self, classification: str) -> List[EvidenceItem]:
        """Returns all evidence items of a given classification."""
        eids = self.index_by_type.get(classification, set())
        return [self.items[eid] for eid in sorted(eids) if eid in self.items]

    def get_evidence_by_id(self, evidence_id: str) -> Optional[EvidenceItem]:
        """Average-case O(1) lookup by evidence_id."""
        return self.get_item(evidence_id)

    def get_evidence_for_entity(self, entity: str) -> List[EvidenceItem]:
        """Returns all evidence items mentioning or relating to an entity."""
        return self.get_by_entity(entity)

    def get_evidence_for_record(self, record_id: str) -> List[EvidenceItem]:
        """Returns all evidence items referencing a source record."""
        return self.get_by_record(record_id)

    def get_evidence_for_anomaly(self, anomaly_id: str) -> List[EvidenceItem]:
        """Returns evidence items associated with an anomaly ID or pattern."""
        it = self.get_by_anomaly(anomaly_id)
        if it:
            return [it]
        slug_target = _slug(anomaly_id)
        matches = []
        for item in self.items.values():
            if item.evidence_type == EvidenceClassification.ANOMALY_SIGNAL:
                if (
                    item.metadata.get("anomaly_id") == anomaly_id
                    or slug_target in item.evidence_id
                    or ("BURST" in anomaly_id and item.metadata.get("pattern") == "burst_activity")
                ):
                    matches.append(item)
        return matches

    def get_evidence_for_relationship(self, u: str, v: str) -> Optional[EvidenceItem]:
        """Returns relationship evidence between two entities (order-invariant)."""
        return self.get_by_relationship(u, v)

    def build_trace(self, target_id: str, target_type: str = None) -> Optional[EvidenceTrace]:
        """Builds a multi-hop provenance trace for a target ID or finding."""
        item = self.get_item(target_id)
        if not item:
            anoms = self.get_evidence_for_anomaly(target_id)
            if anoms:
                item = anoms[0]
        if not item:
            recs = self.get_by_record(target_id)
            if recs:
                item = recs[0]
        if not item:
            ents = self.get_by_entity(target_id)
            if ents:
                item = ents[0]
        if item:
            return self.compile_trace(item.evidence_id)
        return None

    def get_summary(self) -> Dict[str, Any]:
        """Returns corpus-level provenance and evidence metrics."""
        type_counts = {t: len(s) for t, s in self.index_by_type.items()}
        epistemic_counts = {}
        for item in self.items.values():
            epistemic_counts[item.epistemic_status] = epistemic_counts.get(item.epistemic_status, 0) + 1

        return {
            "total_evidence_items": len(self.items),
            "indexed_entities": len(self.index_by_entity),
            "indexed_records": len(self.index_by_record),
            "indexed_relationships": len(self.index_by_relationship),
            "indexed_anomalies": len(self.index_by_anomaly),
            "counts_by_classification": type_counts,
            "counts_by_epistemic_status": epistemic_counts,
            "epistemic_guardrails_enforced": True,
        }

    def compile_trace(self, evidence_id: str) -> Optional[EvidenceTrace]:
        """
        Builds a step-by-step provenance trace from raw records to the given finding.
        """
        item = self.get_item(evidence_id)
        if not item:
            return None

        steps = []
        # Step 1: Raw Ingested Source Records
        for rid in item.source_records:
            rec_item = self.get_item(f"EVID-REC-{_slug(rid)}")
            excerpts = [ex["verbatim_text"] for ex in item.raw_excerpts if ex.get("record_id") == rid]
            verbatim = excerpts[0] if excerpts else (rec_item.finding if rec_item else "")
            steps.append({
                "stage": "source_records",
                "stage_label": "1. Source Record Ingestion",
                "epistemic_status": EpistemicStatus.OBSERVED,
                "record_id": rid,
                "source": rec_item.metadata.get("source", "unknown") if rec_item else "unknown",
                "date": rec_item.temporal_context if rec_item else "",
                "description": f"Record {rid} ingested with verbatim narrative text.",
                "verbatim_excerpt": verbatim,
            })

        # Step 2: Entity Observations
        if item.entities:
            steps.append({
                "stage": "entity_observation",
                "stage_label": "2. Entity Extraction & Normalization",
                "epistemic_status": EpistemicStatus.OBSERVED,
                "entities_observed": item.entities,
                "description": f"Extracted entities {item.entities} mentioned within source text.",
            })

        # Step 3: Analytical Transformation / Detection
        steps.append({
            "stage": "analytical_detection",
            "stage_label": f"3. {item.evidence_type.replace('_', ' ').title()} Formulation",
            "epistemic_status": item.epistemic_status,
            "analytical_method": item.analytical_method,
            "rationale": item.rationale,
            "limitations": item.limitations,
        })

        return EvidenceTrace(
            target_id=item.metadata.get("target_id", item.evidence_id),
            target_type=item.evidence_type,
            evidence_id=item.evidence_id,
            steps=steps,
        )

    # ── Compilation from Pipeline Outputs ──────────────────────────────────────

    def compile_corpus(
        self,
        records=None,
        extracted=None,
        G=None,
        centrality=None,
        key_players=None,
        bridges=None,
        anomalies=None,
        resolution_engine=None,
        canonical_registry=None,
        **kwargs,
    ):
        """
        Compiles the entire evidence bundle from existing pipeline outputs or corpus dict.
        Does NOT recompute extraction, graph construction, or anomaly detection.
        Strictly builds provenance links, raw excerpts, and explanations.
        """
        if isinstance(records, dict):
            corpus = records
            records = corpus.get("records", [])
            extracted = []
            for r in records:
                ex_ents = []
                ents_source = r.get("extracted_entities", []) if isinstance(r, dict) else getattr(r, "extracted_entities", [])
                for e in ents_source:
                    if isinstance(e, dict):
                        ex_ents.append(type("Ent", (), {"text": e.get("text", ""), "label": e.get("label", "UNKNOWN")}))
                    else:
                        ex_ents.append(e)
                rid = r.get("record_id") if isinstance(r, dict) else getattr(r, "record_id", "")
                extracted.append(type("Extracted", (), {"record_id": rid, "entities": ex_ents}))

            import networkx as nx
            G = nx.MultiGraph()
            for n in corpus.get("nodes", []):
                nid = n.get("id") if isinstance(n, dict) else getattr(n, "id", "")
                ntype = n.get("type") if isinstance(n, dict) else getattr(n, "type", "UNKNOWN")
                G.add_node(nid, type=ntype)
            for e in corpus.get("edges", []):
                u = e.get("source") if isinstance(e, dict) else getattr(e, "source", "")
                v = e.get("target") if isinstance(e, dict) else getattr(e, "target", "")
                w = e.get("weight", 1) if isinstance(e, dict) else getattr(e, "weight", 1)
                recs = e.get("records", []) if isinstance(e, dict) else getattr(e, "records", [])
                dates = e.get("dates", []) if isinstance(e, dict) else getattr(e, "dates", [])
                G.add_edge(u, v, weight=w, records=recs, dates=dates)

            centrality = {}
            for n in corpus.get("nodes", []):
                nid = n.get("id") if isinstance(n, dict) else getattr(n, "id", "")
                centrality[nid] = n if isinstance(n, dict) else n.__dict__

            key_players = [n for n in corpus.get("nodes", []) if (n.get("is_key_player") if isinstance(n, dict) else getattr(n, "is_key_player", False))]
            bridges = [(n.get("id"), n.get("bridge_betweenness", 0.0)) for n in corpus.get("nodes", []) if (n.get("is_bridge_node") if isinstance(n, dict) else getattr(n, "is_bridge_node", False))]
            anomalies = corpus.get("anomalies", [])
            canonical_registry = corpus.get("canonical_entities", {})

        records = records or []
        extracted = extracted or []

        # 1. Source Records Evidence
        rec_map = {}
        for r in records:
            rid = getattr(r, "record_id", None) or (r.get("record_id") if isinstance(r, dict) else None)
            source = getattr(r, "source", None) or (r.get("source", "unknown") if isinstance(r, dict) else "unknown")
            date = getattr(r, "date", None) or (r.get("date", "") if isinstance(r, dict) else "")
            text = getattr(r, "text", None) or (r.get("text", "") if isinstance(r, dict) else "")
            rec_map[rid] = {"source": source, "date": date, "text": text}

            eid = f"EVID-REC-{_slug(rid)}"
            self.register_item(EvidenceItem(
                evidence_id=eid,
                evidence_type=EvidenceClassification.SOURCE_RECORD,
                epistemic_status=EpistemicStatus.OBSERVED,
                finding=f"Ingested record {rid} from {source.replace('_', ' ').title()}",
                source_records=[rid],
                raw_excerpts=[{
                    "record_id": rid,
                    "source": source,
                    "date": date,
                    "verbatim_text": text,
                    "byte_offset_start": 0,
                    "byte_offset_end": len(text),
                }],
                entities=[],
                temporal_context=date,
                spatial_context=None,
                analytical_method="Direct connector ingestion via BaseConnector (idempotent)",
                rationale=f"Original incident report document ingested from {source} on {date}.",
                limitations=LIMITATIONS_SOURCE_RECORD,
                references=[],
                metadata={"record_id": rid, "source": source, "date": date},
            ))

        # 2. Entity Observation Evidence
        extracted_by_rec = {}
        for ex in extracted:
            rid = getattr(ex, "record_id", "")
            extracted_by_rec[rid] = ex

            for ent in getattr(ex, "entities", []):
                ename = getattr(ent, "text", "")
                elabel = getattr(ent, "label", "UNKNOWN")
                eid = f"EVID-OBS-{_slug(rid)}-{_slug(ename)}"
                raw_rec = rec_map.get(rid, {})
                raw_text = raw_rec.get("text", "")
                idx = raw_text.find(ename)
                if idx == -1:
                    idx = raw_text.lower().find(ename.lower())
                if idx != -1:
                    b_start = idx
                    b_end = idx + len(ename)
                    v_text = raw_text[b_start:b_end]
                else:
                    b_start = 0
                    b_end = len(raw_text)
                    v_text = raw_text

                self.register_item(EvidenceItem(
                    evidence_id=eid,
                    evidence_type=EvidenceClassification.ENTITY_OBSERVATION,
                    epistemic_status=EpistemicStatus.OBSERVED,
                    finding=f"Observed {elabel} entity '{ename}' in record {rid}",
                    source_records=[rid],
                    raw_excerpts=[{
                        "record_id": rid,
                        "source": raw_rec.get("source", "unknown"),
                        "date": raw_rec.get("date", ""),
                        "verbatim_text": v_text,
                        "byte_offset_start": b_start,
                        "byte_offset_end": b_end,
                    }],
                    entities=[ename],
                    temporal_context=raw_rec.get("date", ""),
                    spatial_context=ename if elabel == "LOCATION" else None,
                    analytical_method="RuleBasedNER regex and gazetteer surface extraction",
                    rationale=f"Explicit entity mention '{ename}' extracted from verbatim narrative of record {rid}.",
                    limitations=f"Surface observation of '{ename}' within {rid}. Presence does not prove independent activity outside this mention.",
                    references=[EvidenceReference(target_id=rid, target_type="RECORD", description=f"Source record {rid}")],
                    metadata={"entity_name": ename, "entity_type": elabel, "record_id": rid},
                ))

        # 3. Relationship Co-occurrence Evidence
        if G is not None:
            for u, v, d in G.edges(data=True):
                cp = canonical_pair(u, v)
                eid = f"EVID-REL-{_slug(cp[0])}--{_slug(cp[1])}"
                weight = d.get("weight", 1)
                edge_records = d.get("records", [])
                edge_dates = d.get("dates", [])

                excerpts = []
                for rid in edge_records:
                    if rid in rec_map:
                        rtxt = rec_map[rid]["text"]
                        excerpts.append({
                            "record_id": rid,
                            "source": rec_map[rid]["source"],
                            "date": rec_map[rid]["date"],
                            "verbatim_text": rtxt,
                            "byte_offset_start": 0,
                            "byte_offset_end": len(rtxt),
                        })

                dates_str = ", ".join(sorted(list(set(edge_dates)))) if edge_dates else "None"
                recs_str = ", ".join(sorted(list(set(edge_records))))

                self.register_item(EvidenceItem(
                    evidence_id=eid,
                    evidence_type=EvidenceClassification.RELATIONSHIP,
                    epistemic_status=EpistemicStatus.DERIVED,
                    finding=f"Co-occurrence relationship between '{cp[0]}' and '{cp[1]}' (Weight: {weight})",
                    source_records=sorted(list(set(edge_records))),
                    raw_excerpts=excerpts,
                    entities=[cp[0], cp[1]],
                    temporal_context=dates_str,
                    spatial_context=None,
                    analytical_method="Bipartite graph projection of pairwise co-occurrences across records",
                    rationale=(
                        f"Entities '{cp[0]}' and '{cp[1]}' co-occurred together across {weight} independent record(s): "
                        f"{recs_str} on date(s) {dates_str}."
                    ),
                    limitations=LIMITATIONS_RELATIONSHIP,
                    references=[
                        EvidenceReference(target_id=r, target_type="RECORD", description=f"Supporting record {r}")
                        for r in sorted(list(set(edge_records)))
                    ],
                    metadata={
                        "source_entity": cp[0],
                        "target_entity": cp[1],
                        "weight": weight,
                        "dates": sorted(list(set(edge_dates))),
                    },
                ))

        # 4. Network Metric Evidence
        if centrality and G is not None:
            kp_dict = {(p.get("entity") or p.get("id")): p for p in key_players}
            bridge_dict = {b[0]: b[1] for b in bridges} if bridges else {}

            for node, metrics in centrality.items():
                deg = metrics.get("degree", 0.0)
                bet = metrics.get("betweenness", 0.0)
                eig = metrics.get("eigenvector", 0.0)
                pr = metrics.get("pagerank", 0.0)
                ntype = metrics.get("type", "UNKNOWN")

                kp_data = kp_dict.get(node)
                comp_score = kp_data.get("influence_score") if kp_data else round(
                    0.25 * deg + 0.35 * bet + 0.25 * eig + 0.15 * pr, 4
                )
                is_kp = node in kp_dict
                is_br = node in bridge_dict

                eid = f"EVID-METRIC-{_slug(node)}-CENTRALITY"

                # Find records where node appears
                node_recs = []
                for rid, rdata in rec_map.items():
                    if node.lower() in rdata["text"].lower():
                        node_recs.append(rid)

                excerpts = []
                for r in node_recs:
                    if r in rec_map:
                        rtxt = rec_map[r]["text"]
                        excerpts.append({
                            "record_id": r,
                            "source": rec_map[r]["source"],
                            "date": rec_map[r]["date"],
                            "verbatim_text": rtxt,
                            "byte_offset_start": 0,
                            "byte_offset_end": len(rtxt),
                        })

                self.register_item(EvidenceItem(
                    evidence_id=eid,
                    evidence_type=EvidenceClassification.NETWORK_METRIC,
                    epistemic_status=EpistemicStatus.DERIVED,
                    finding=(
                        f"Network centrality profile for '{node}' ({ntype}): "
                        f"Composite Influence={comp_score}, Degree={deg:.4f}, Betweenness={bet:.4f}"
                    ),
                    source_records=node_recs,
                    raw_excerpts=excerpts,
                    entities=[node],
                    temporal_context=None,
                    spatial_context=node if ntype == "LOCATION" else None,
                    analytical_method=(
                        "Composite influence formula: 0.25 * degree + 0.35 * betweenness + 0.25 * eigenvector + 0.15 * PageRank. "
                        "Degree and betweenness computed via NetworkX on undirected multi-record graph."
                    ),
                    rationale=(
                        f"Entity '{node}' connects to {G.degree(node) if G.has_node(node) else 0} neighbors in graph topology. "
                        f"Degree Centrality: {deg:.4f}, Betweenness: {bet:.4f}, Eigenvector: {eig:.4f}, PageRank: {pr:.4f}. "
                        + ("Ranked as a Key Player. " if is_kp else "")
                        + ("Identified as a critical structural bridge node. " if is_br else "")
                    ),
                    limitations=LIMITATIONS_NETWORK_METRIC,
                    references=[
                        EvidenceReference(target_id=node, target_type="ENTITY", description=f"Entity {node}"),
                    ],
                    metadata={
                        "entity": node,
                        "composite_influence": comp_score,
                        "degree": deg,
                        "betweenness": bet,
                        "eigenvector": eig,
                        "pagerank": pr,
                        "is_key_player": is_kp,
                        "is_bridge_node": is_br,
                    },
                ))

        # 5. Anomaly Signal Evidence
        if anomalies:
            for idx, anom in enumerate(anomalies):
                anom_id = anom.get("id") or f"ANOM-{idx+1:03d}"
                pattern = anom.get("pattern", "unknown")
                ent = anom.get("entity")
                rid = anom.get("record_id")
                date = anom.get("date")
                note = anom.get("note", "")

                involved_ents = [ent] if ent else []
                involved_recs = [rid] if rid else []

                # If entity present, gather supporting records
                if ent and not involved_recs:
                    for r, rdata in rec_map.items():
                        if ent.lower() in rdata["text"].lower():
                            involved_recs.append(r)

                excerpts = []
                for r in involved_recs:
                    if r in rec_map:
                        rtxt = rec_map[r]["text"]
                        excerpts.append({
                            "record_id": r,
                            "source": rec_map[r]["source"],
                            "date": rec_map[r]["date"],
                            "verbatim_text": rtxt,
                            "byte_offset_start": 0,
                            "byte_offset_end": len(rtxt),
                        })

                # Specific analytical method and detector config per pattern
                if pattern == "burst_activity":
                    method = "Temporal event clustering detector (Config: min_events=5, window_hours=2)"
                elif pattern == "structuring":
                    method = "Financial structuring text heuristic (Reporting threshold: INR 200,000 / split deposits)"
                elif pattern == "new_entity_spike":
                    method = "Graph topological recruitment detector (Rule: first appearance linked to >=2 previously known entities)"
                elif pattern == "statistical_outlier":
                    method = "Scikit-Learn IsolationForest over 4D centrality feature space (degree, betweenness, eigenvector, pagerank; contamination=0.15, seed=42)"
                else:
                    method = f"Algorithmic anomaly pattern detector: {pattern}"

                eid = f"EVID-ANOM-{_slug(anom_id)}"
                self.register_item(EvidenceItem(
                    evidence_id=eid,
                    evidence_type=EvidenceClassification.ANOMALY_SIGNAL,
                    epistemic_status=EpistemicStatus.SIGNAL,
                    finding=f"Anomaly Signal [{pattern.replace('_', ' ').title()}] - {anom_id}",
                    source_records=involved_recs,
                    raw_excerpts=excerpts,
                    entities=involved_ents,
                    temporal_context=date,
                    spatial_context=None,
                    analytical_method=method,
                    rationale=note or f"Pattern '{pattern}' triggered by detector for {ent or rid}.",
                    limitations=LIMITATIONS_ANOMALY,
                    references=[
                        EvidenceReference(target_id=anom_id, target_type="ANOMALY", description=f"Anomaly {anom_id}")
                    ] + [
                        EvidenceReference(target_id=r, target_type="RECORD", description=f"Source record {r}")
                        for r in involved_recs
                    ],
                    metadata={
                        "anomaly_id": anom_id,
                        "pattern": pattern,
                        "entity": ent,
                        "record_id": rid,
                        "date": date,
                        "event_count": anom.get("event_count"),
                    },
                ))

        # 6. Entity Resolution Evidence (Phase 3G Integration)
        if canonical_registry:
            for can_id, ce in canonical_registry.items():
                if hasattr(ce, "to_dict"):
                    ce_dict = ce.to_dict()
                else:
                    ce_dict = ce

                cname = ce_dict.get("canonical_name", can_id)
                ctype = ce_dict.get("entity_type", "UNKNOWN")
                review_status = ce_dict.get("review_status", "RESOLVED")
                variants = ce_dict.get("observed_variants", [])
                source_recs = ce_dict.get("source_records", [])
                review_reasons = ce_dict.get("review_reasons", [])

                excerpts = []
                for r in source_recs:
                    if r in rec_map:
                        rtxt = rec_map[r]["text"]
                        excerpts.append({
                            "record_id": r,
                            "source": rec_map[r]["source"],
                            "date": rec_map[r]["date"],
                            "verbatim_text": rtxt,
                            "byte_offset_start": 0,
                            "byte_offset_end": len(rtxt),
                        })

                eid = f"EVID-RES-{_slug(can_id)}"
                ep_status = (
                    EpistemicStatus.REVIEW_REQUIRED
                    if review_status == "REVIEW_REQUIRED"
                    else EpistemicStatus.DERIVED
                )

                rationale_text = (
                    f"Canonical entity '{cname}' resolved across {len(variants)} observed variant(s): {', '.join(variants)}. "
                    f"Mentioned in {len(source_recs)} record(s)."
                )
                if review_reasons:
                    rationale_text += f" Review Required Reasons: {'; '.join(review_reasons)}"

                self.register_item(EvidenceItem(
                    evidence_id=eid,
                    evidence_type=EvidenceClassification.ENTITY_RESOLUTION,
                    epistemic_status=ep_status,
                    finding=f"Entity Resolution for '{cname}' ({ctype}) - Status: {review_status}",
                    source_records=source_recs,
                    raw_excerpts=excerpts,
                    entities=[cname] + [v for v in variants if v != cname],
                    temporal_context=None,
                    spatial_context=cname if ctype == "LOCATION" else None,
                    analytical_method=(
                        "Deterministic normalization (Unicode NFKC, honorific stripping, contact normalization), "
                        "blocking candidate generation, multi-signal feature extraction, and resolution policy guardrails."
                    ),
                    rationale=rationale_text,
                    limitations=LIMITATIONS_ENTITY_RESOLUTION,
                    references=[
                        EvidenceReference(target_id=r, target_type="RECORD", description=f"Observation source record {r}")
                        for r in source_recs
                    ],
                    metadata={
                        "canonical_id": can_id,
                        "canonical_name": cname,
                        "entity_type": ctype,
                        "review_status": review_status,
                        "review_reasons": review_reasons,
                        "observed_variants": variants,
                    },
                ))

        # 7. Location Observation Evidence
        loc_entities = [n for n in G.nodes() if G.nodes[n].get("type") == "LOCATION"] if G is not None else []
        for loc in loc_entities:
            loc_recs = []
            for r, rdata in rec_map.items():
                if loc.lower() in rdata["text"].lower():
                    loc_recs.append(r)

            excerpts = []
            for r in loc_recs:
                if r in rec_map:
                    rtxt = rec_map[r]["text"]
                    excerpts.append({
                        "record_id": r,
                        "source": rec_map[r]["source"],
                        "date": rec_map[r]["date"],
                        "verbatim_text": rtxt,
                        "byte_offset_start": 0,
                        "byte_offset_end": len(rtxt),
                    })

            eid = f"EVID-LOC-{_slug(loc)}"
            self.register_item(EvidenceItem(
                evidence_id=eid,
                evidence_type=EvidenceClassification.LOCATION_OBSERVATION,
                epistemic_status=EpistemicStatus.OBSERVED,
                finding=f"Operational / Incident site observation: '{loc}'",
                source_records=loc_recs,
                raw_excerpts=excerpts,
                entities=[loc],
                temporal_context=None,
                spatial_context=loc,
                analytical_method="Geographical entity extraction & graph spatial hub identification",
                rationale=f"Site '{loc}' mentioned across {len(loc_recs)} incident report(s): {', '.join(loc_recs)}.",
                limitations=LIMITATIONS_LOCATION,
                references=[
                    EvidenceReference(target_id=loc, target_type="LOCATION", description=f"Location node {loc}"),
                ],
                metadata={"location_name": loc, "source_records": loc_recs},
            ))

        # 8. Temporal Observation Evidence
        for rid, rdata in rec_map.items():
            date_val = rdata.get("date")
            if date_val:
                eid = f"EVID-TIME-{_slug(rid)}-{_slug(date_val)}"
                rtxt = rdata.get("text", "")
                self.register_item(EvidenceItem(
                    evidence_id=eid,
                    evidence_type=EvidenceClassification.TEMPORAL_OBSERVATION,
                    epistemic_status=EpistemicStatus.OBSERVED,
                    finding=f"Chronological incident date '{date_val}' documented in {rid}",
                    source_records=[rid],
                    raw_excerpts=[{
                        "record_id": rid,
                        "source": rdata.get("source", "unknown"),
                        "date": date_val,
                        "verbatim_text": rtxt,
                        "byte_offset_start": 0,
                        "byte_offset_end": len(rtxt),
                    }],
                    entities=[],
                    temporal_context=date_val,
                    spatial_context=None,
                    analytical_method="Temporal date extraction from source metadata and chronological timeline sequencing",
                    rationale=f"Incident event timestamp recorded as {date_val} in record {rid}.",
                    limitations=LIMITATIONS_TEMPORAL,
                    references=[
                        EvidenceReference(target_id=rid, target_type="RECORD", description=f"Record {rid}"),
                    ],
                    metadata={"record_id": rid, "date": date_val},
                ))

